### ISSUE TITLE
adding points

### ISSUE THREAD

**Issue by fackir** [Tmktahu/atlas#34]
It would be nice to be able to add independent points to the map. there is no coordinate grid on the moon, but if you could add points indicating the distance from several objects in km, then you could get a visual map.

**Comment by Tmktahu** [comment]
@fackir I don't quite follow. Are you talking about custom user waypoints or the default waypoints like gates and origin stations?

And then are you talking about adding a point on the map based on its distance to other objects?

**Comment by Tmktahu** [comment]
@fackir Given I haven't heard from you, I'm gunna close this issue. I've created another regarding freestyle-point creation if that's what you were talking about #68
